fileobject1 = open("fajl1.txt", "r")
fileobject2 = open("fajl2.txt","r")
output_fileobject = open("fajl1_es_fajl2_txt", "w")
line1 = fileobject1.readline()
line2 = fileobject2.readline()
while line1 != "" or line2 != "":
    output_fileobject.write(line1)
    output_fileobject.write(line2)
    line1 = fileobject1.readline()
    line2 = fileobject2.readline()
fileobject1.close()
fileobject2.close()
output_fileobject.close()